/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SongListDialog.java
 *
 * Created on 14.07.2010, 12:50:23
 */

package uslr;

import java.io.File;
import javax.swing.JFileChooser;
import org.jdesktop.application.Action;

/**
 *
 * @author sebastian
 */
public class SongListDialog extends java.awt.Dialog {

    /** Creates new form SongListDialog */
    public SongListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        songDirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        outDirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        songDirLabel = new javax.swing.JLabel();
        songDirField = new javax.swing.JTextField();
        chooseSongDirButton = new javax.swing.JButton();
        outDirLabel = new javax.swing.JLabel();
        outDirField = new javax.swing.JTextField();
        chooseOutDirButton = new javax.swing.JButton();
        createSongListButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uslr.USLRApp.class).getContext().getResourceMap(SongListDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        songDirLabel.setText(resourceMap.getString("songDirLabel.text")); // NOI18N
        songDirLabel.setName("songDirLabel"); // NOI18N

        songDirField.setText(resourceMap.getString("songDirField.text")); // NOI18N
        songDirField.setName("songDirField"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(uslr.USLRApp.class).getContext().getActionMap(SongListDialog.class, this);
        chooseSongDirButton.setAction(actionMap.get("chooseSongDir")); // NOI18N
        chooseSongDirButton.setText(resourceMap.getString("chooseSongDirButton.text")); // NOI18N
        chooseSongDirButton.setName("chooseSongDirButton"); // NOI18N

        outDirLabel.setText(resourceMap.getString("outDirLabel.text")); // NOI18N
        outDirLabel.setName("outDirLabel"); // NOI18N

        outDirField.setName("outDirField"); // NOI18N

        chooseOutDirButton.setAction(actionMap.get("chooseOutDir")); // NOI18N
        chooseOutDirButton.setText(resourceMap.getString("chooseOutDirButton.text")); // NOI18N
        chooseOutDirButton.setName("chooseOutDirButton"); // NOI18N

        createSongListButton.setAction(actionMap.get("createSongList")); // NOI18N
        createSongListButton.setText(resourceMap.getString("createSongListButton.text")); // NOI18N
        createSongListButton.setName("createSongListButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createSongListButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outDirLabel)
                            .addComponent(songDirLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(songDirField)
                            .addComponent(outDirField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseSongDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooseOutDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(songDirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseSongDirButton)
                    .addComponent(songDirLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outDirLabel)
                    .addComponent(outDirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseOutDirButton))
                .addGap(18, 18, 18)
                .addComponent(createSongListButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SongListDialog dialog = new SongListDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void chooseSongDir() {
        if(songDirChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            songDirField.setText(songDirChooser.getSelectedFile().getPath());
        }
    }

    @Action
    public void chooseOutDir() {
        if(outDirChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            outDirField.setText(outDirChooser.getSelectedFile().getPath());
        }
    }

    @Action
    public void createSongList() {
        (new SongListMaker(new File(songDirField.getText()),
                new File(outDirField.getText()))).create();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseOutDirButton;
    private javax.swing.JButton chooseSongDirButton;
    private javax.swing.JButton createSongListButton;
    private javax.swing.JTextField outDirField;
    private javax.swing.JLabel outDirLabel;
    private javax.swing.JTextField songDirField;
    private javax.swing.JLabel songDirLabel;
    // End of variables declaration//GEN-END:variables

    private final JFileChooser songDirChooser = new JFileChooser();
    private final JFileChooser outDirChooser = new JFileChooser();
}
